<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateTikTokAttendance extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tik_tok_attendance', function (Blueprint $table) {
            $table->increments('id');
            $table->string('emp_mx_id')->comment = "Employee Id with Mx Prefix";
            $table->string('emp_name');
            $table->integer('punch_trg_id')->comment = "Id generated by bio-metric device on each punch. Reference number to native Db";
            $table->dateTime('punch_trg_datetime')->comment = "Date time generated by bio-metric device";
            $table->date('punch_trg_date')->comment = "Date generated by bio-metric device";
            $table->string('punch_type', 6)->comment = "Tpye: In or Out";

            $table->unique('punch_trg_id', 'pun_trg_id_unique');

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('tik_tok_attendance');
    }
}
